"""first migration

Revision ID: 6863138dd202
Revises: 
Create Date: 2023-03-24 14:49:31.488144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6863138dd202'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=9), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.CheckConstraint('LENGTH(username) >= 5 AND LENGTH(username)<=9'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('short_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short_url_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('short_url_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['short_url_id'], ['short_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_url_pairs')
    op.drop_table('short_urls')
    op.drop_table('users')
    # ### end Alembic commands ###
